"""add request metrics

Revision ID: 3d330ede56b0
Revises: c425b8105172
Create Date: 2026-08-12 17:01:05.432145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d330ede56b0'
down_revision: Union[str, Sequence[str], None] = 'c425b8105172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('endpoint', sa.String(length=64), nullable=False),
    sa.Column('stage_latencies_ms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_metrics_endpoint'), 'request_metrics', ['endpoint'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate always falsely detects the hand-written GIN (content_tsv)
    # and HNSW (embedding) indexes on document_chunks as "removed" since they were
    # created via raw op.execute() rather than the ORM/op.create_index — stripped
    # the false-positive drop/recreate pair here, same as every prior migration
    # that touches document_chunks — see prior migrations for the same fix.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_metrics_endpoint'), table_name='request_metrics')
    op.drop_table('request_metrics')
    # ### end Alembic commands ###
