"""add auth: users, roles, document permissions

Revision ID: 58ce56256af0
Revises: ea2d92e73140
Create Date: 2026-08-11 22:02:35.967262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ce56256af0'
down_revision: Union[str, Sequence[str], None] = 'ea2d92e73140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.execute("INSERT INTO roles (id, name) VALUES (gen_random_uuid(), 'admin'), (gen_random_uuid(), 'user')")
    op.create_table('document_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('role_id', sa.Uuid(), nullable=True),
    sa.Column('permission_level', sa.String(length=16), nullable=False),
    sa.CheckConstraint('(user_id IS NOT NULL) OR (role_id IS NOT NULL)', name='ck_document_permission_target'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('conversations', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'])
    # NOTE: autogenerate wants to drop+recreate document_chunks_content_tsv_idx (gin) and
    # document_chunks_embedding_hnsw_idx (hnsw) here — false positive, it doesn't recognize
    # index types created via raw op.execute() in earlier migrations as matching the model.
    # Deliberately not touching them; see the corresponding removal in downgrade() below.
    op.add_column('documents', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'documents', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'owner_id')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'user_id')
    op.drop_table('document_permissions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.execute("DELETE FROM roles WHERE name IN ('admin', 'user')")
    op.drop_table('roles')
    # ### end Alembic commands ###
